# Dependabot version updates.
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # package.json / package-lock.json
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions" # .github/workflows/*
    directory: "/"
    schedule:
      interval: "weekly"
